"""Local retrieval helpers."""

from private_memory_agent.retrieval.embeddings import (
    EmbeddedDocument,
    EmbeddingIndexResult,
    EmbeddingModel,
    FakeEmbeddingModel,
    HashEmbeddingModel,
    InMemoryVectorStore,
    QdrantVectorStore,
    SemanticSearchResult,
    SentenceTransformersEmbeddingModel,
    VectorSearchResult,
    VectorStore,
    index_embeddings,
    semantic_search,
)
from private_memory_agent.retrieval.evidence import (
    Evidence,
    REDACTED_TEXT,
    RetrievalFilters,
    RetrievalResult,
    RetrievalService,
    pack_evidence_for_prompt,
)
from private_memory_agent.retrieval.text import (
    TextSearchDiagnostics,
    TextIndexResult,
    TextSearchResult,
    diagnose_text_search,
    extract_query_terms,
    index_text,
    media_annotation_search_text,
    search_text,
)

__all__ = [
    "EmbeddedDocument",
    "EmbeddingIndexResult",
    "EmbeddingModel",
    "Evidence",
    "FakeEmbeddingModel",
    "HashEmbeddingModel",
    "InMemoryVectorStore",
    "QdrantVectorStore",
    "REDACTED_TEXT",
    "RetrievalFilters",
    "RetrievalResult",
    "RetrievalService",
    "SemanticSearchResult",
    "SentenceTransformersEmbeddingModel",
    "TextSearchDiagnostics",
    "TextIndexResult",
    "TextSearchResult",
    "VectorSearchResult",
    "VectorStore",
    "diagnose_text_search",
    "extract_query_terms",
    "index_embeddings",
    "index_text",
    "media_annotation_search_text",
    "pack_evidence_for_prompt",
    "search_text",
    "semantic_search",
]
